Redux
Finnchick/itechart_final_proj pull request #5
Opened 2021-10-04 15:11 UTC by Finnchick

Implemented basic redux functionality for catalogue clear work

2021-10-05 13:48 UTC, Dekim12 commented on src/App.jsx
>          <Route path={BEER_PAGE}>
can specify path params {`${BEER_PAGE}/:id`} and get these params by useParams hook

2021-10-05 14:11 UTC, Dekim12 requested changes

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/BeerPage.jsx
> +  let id = location.pathname.split("/").slice(-1)[0]; //do this immutable
use useParams

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerFoodPairing/BeerFoodPairing.jsx
> +        <div key={foodPairing.indexOf(string)} className="test">
what doe className test mean?

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerFoodPairing/BeerFoodPairing.jsx
> +          <p key={foodPairing.indexOf(string)}>{string}</p>
define mapping before return statement and define a variable for the key to use foodPairing.indexOf once

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerHead/BeerHead.jsx
> +function BeerHead({ BeerName, BeerTagline, BeerDescription, BeerImgUrl }) {
props should start from lowercase letter

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerIngredients/BeerIngredients.jsx
> +        {maltItem.name} - {maltItem.amount.value} {maltItem.amount.unit}
use template string

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerIngredients/BeerIngredients.jsx
> +  const MALT = ingredients.malt.map((maltItem) => {
can use parameters destructuring for maltItem

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerIngredients/BeerIngredients.jsx
> +  const HOPS = ingredients.hops.map((hopsItem) => {
destructuring

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerMethod/BeerMethod.jsx
> +  const MASH = method.mash_temp.map((item) => {
destructuring

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerMethod/BeerMethod.jsx
> +function BeerMethod({ method }) {
destruct the method

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerProperties/BeerProperties.jsx
> +function BeerProperties({ ABVValue, IBUValue, EBCValue }) {
Not use a capital later

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerProperties/BeerProperties.jsx
> +        <p>IBU</p> <p>{IBUValue}</p>{" "}
use template instead of `<p>IBU</p> <p>{IBUValue}</p>{" "}`

2021-10-05 14:11 UTC, Dekim12 commented on src/pages/BeerPage/Components/BeerSpecification/BeerSpecification.jsx
> +function BeerSpecification({ abvvalue, ibuvalue, ebcvalue, foodPairing }) {
abvValue, ibuValue, ebcValue,  or juct abv, ibu, ebc

2021-10-05 14:11 UTC, Dekim12 commented on src/redux/store/store.jsx
> +    BeerReducer,
also start reducer from lowercase letter

2021-10-05 14:11 UTC, Dekim12 commented on src/redux/store/store.jsx
> +import BeerReducer from "../slices/beerDataSlice";
empty sting

2021-10-05 14:11 UTC, Dekim12 commented on src/redux/thunks/thunks.jsx
> +import { fetchWithoutParams } from "../../constants";
imports

2021-10-07 13:44 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerFoodPairing/BeerFoodPairing.jsx
> +        <div key={foodPairing.indexOf(string)} className="test">
changed to foodPairing

2021-10-07 15:47 UTC, Finnchick commented on src/App.jsx
>          <Route path={BEER_PAGE}>
I didn't know it before, very usefull thing, thank you!

2021-10-07 15:51 UTC, Finnchick commented on src/pages/BeerPage/BeerPage.jsx
> +  let id = location.pathname.split("/").slice(-1)[0]; //do this immutable
Done

2021-10-07 16:28 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerFoodPairing/BeerFoodPairing.jsx
> +          <p key={foodPairing.indexOf(string)}>{string}</p>
Done

2021-10-07 16:35 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerHead/BeerHead.jsx
> +function BeerHead({ BeerName, BeerTagline, BeerDescription, BeerImgUrl }) {
Changed

2021-10-07 16:35 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerIngredients/BeerIngredients.jsx
> +        {maltItem.name} - {maltItem.amount.value} {maltItem.amount.unit}
Changed

2021-10-07 17:50 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerIngredients/BeerIngredients.jsx
> +  const MALT = ingredients.malt.map((maltItem) => {
Why object destruction is so usefull?

2021-10-07 17:51 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerIngredients/BeerIngredients.jsx
> +  const HOPS = ingredients.hops.map((hopsItem) => {
Done

2021-10-07 17:52 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerMethod/BeerMethod.jsx
> +  const MASH = method.mash_temp.map((item) => {
Done

2021-10-07 17:55 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerProperties/BeerProperties.jsx
> +function BeerProperties({ ABVValue, IBUValue, EBCValue }) {
Done

2021-10-07 17:55 UTC, Finnchick commented on src/pages/BeerPage/Components/BeerSpecification/BeerSpecification.jsx
> +function BeerSpecification({ abvvalue, ibuvalue, ebcvalue, foodPairing }) {
Done

2021-10-07 17:57 UTC, Finnchick commented on src/redux/thunks/thunks.jsx
> +import { fetchWithoutParams } from "../../constants";
Done

2021-10-07 17:58 UTC, Finnchick commented on src/redux/store/store.jsx
> +import BeerReducer from "../slices/beerDataSlice";
Added

2021-10-07 18:09 UTC, Finnchick commented on src/redux/store/store.jsx
> +    BeerReducer,
Done

2021-10-07 21:32 UTC, merged